platform :ios, '9.0'

target 'FlowersOrder' do
  use_frameworks!

# Pods for FlowersOrder

  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.0'

  target 'FlowersOrderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlowersOrderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
